services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  BaconQrCodeBundle\Controller\:
    resource: '../../Controller/'
  BaconQrCodeBundle\Service\:
    resource: '../../Service/'
